#ifndef SRC_SETTINGS_CONF_H
#define SRC_SETTINGS_CONF_H

#define WORLD_SIZE_X 30
#define WORLD_SIZE_Y 15
#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 576
#define TILE_SIZE 2
#define PLAYER_SPEED 4.0f

#endif // SRC_SETTINGS_CONF_H
